[project]
name = "fastapi-sample"
version = "0.1.0"
description = "FastAPI Sample"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
]

[dependency-groups]
dev = [
    "ruff>=0.12.1",
]
